add dry-run and verbose arguments

diff --git a/b2e b/b2e
--- a/b2e
+++ b/b2e
@@ -7,41 +7,49 @@ format_usage () {
   fmt -w "$(tput cols)" | colorize
 }
 exception () {
-  echo "$SCRIPT_NAME: ${1:-"unknown error"}" >&2
+  echo "$SCRIPT_NAME: ${1:-"Unknown error"}" >&2
   exit "${2:-1}"
 }
 git_init () {
-  git -C "$ROOT_DIR" init \
+  $DRY_RUN \
+    && exit
+  git -C "$ROOT_DIR" init $VERBOSE \
     && echo -e "/*\n!.gitignore\n!/$RES_DIR" > .gitignore \
-    && git_commit "Init git" \
+    && git_commit "Init git" "--quiet --allow-empty" \
+    || exit 1
+}
+git_checkout () {
+  $DRY_RUN \
+    && return
+  BRANCH_EXISTS="$(git -C "$ROOT_DIR" branch | grep "^\  $1$")"
+  git -C "$ROOT_DIR" checkout $VERBOSE -B "$1" \
+    || exit 1
+  [[ "$BRANCH_EXISTS" != "" ]] \
+    && return
+  rm -rf "$ROOT_DIR/$RES_DIR" \
+    && git_commit "Init branch $1" "--quiet --allow-empty" \
     || exit 1
 }
 git_commit () {
-  local MSG
-  MSG=${1:-"$SCRIPT_NAME autocommit"}
-  ERR="$(git -C "$ROOT_DIR" add --all 2>&1)" \
-    || exception "$ERR"
-  git -C "$ROOT_DIR" commit --allow-empty -qam "$MSG" \
-    || exit 1
+  $DRY_RUN \
+    && return
+  git -C "$ROOT_DIR" add --all \
+    && git -C "$ROOT_DIR" commit $2 -am "$SCRIPT_NAME: ${1:-"No message"}" | head -n2
+  return $?
 }
 git_status () {
   git -C "$ROOT_DIR" status --porcelain 2>&1 \
     || exit 1
 }
-git_branch () {
-  rm -rf "$ROOT_DIR/$RES_DIR" \
-    || exception "Unable to delete folder $ROOT_DIR/$RES_DIR"
-  git -C "$ROOT_DIR" checkout -qb "$1" \
-    && echo "Switched to new branch $1" \
-    && git_commit "Init branch $1"
-}
 
 RES_DIR="src"
 ROOT_DEPTH=1
+DRY_RUN=false
+VERBOSE="--quiet"
 SCRIPT_NAME="$(basename "$0")"
 USAGE="$(cat << STR | format_usage
 DESCRIPTION
-       $SCRIPT_NAME copies (synces) files from SOURCE folder into DESTINATION on corresponding branches using git.
+       $SCRIPT_NAME synces files from SOURCE folder into DESTINATION on corresponding branches using git.
        
 USAGE 
        $SCRIPT_NAME [-h] [-r N] SOURCE [DESTINATION]
@@ -50,22 +58,30 @@ OPTIONS
        -h, --help
               Display this usage.
 
+       -n, --dry-run
+              Perform a trial run with no changes made.
+
        -p N, --parent-folder=N
               Preserve N parent folders from SOURCE (default 1).
+
+       -v, --verbose
+              Increase verbosity
 STR
 )"
 
 LINE=$(getopt \
   -n "$0" \
-  -o p:h \
-  -l parent-folder:,help \
+  -o hnp:v \
+  -l help,dry-run,parent-folder,verbose: \
   -- "$@") \
   || exit 1
 eval set -- "$LINE"
 while [ $# -gt 0 ]; do 
   case $1 in
-    -p|--parent-folder) ROOT_DEPTH="$2"; shift 2 ;;
     -h|--help) echo -e "$USAGE" && exit 0 ;;
+    -n|--dry-run) DRY_RUN=true; shift ;;
+    -p|--parent-folder) ROOT_DEPTH="$2"; shift 2 ;;
+    -v|--verbose) VERBOSE=""; shift ;;
     --) shift; break ;;
     *-) exception "Unrecognized option '$1'" 2 ;;
      *) break ;;
@@ -86,22 +102,17 @@ ROOT_DIR="${2:-.}"
 [[ -d "$ROOT_DIR/.git" ]] \
   || git_init
 [[ -z "$(git_status)" ]] \
-  || git_commit
+  || git_commit "Autocommit" "$VERBOSE"
 
 PRJ_DIR="$(realpath "$SRC_DIR" | rev | cut -d "/" -f-"$ROOT_DEPTH" | rev)"
 BRANCH_NAME="$(echo "$PRJ_DIR" | tr "/" "-")"
 DEST_DIR="$ROOT_DIR/$RES_DIR/$(echo "$PRJ_DIR/" | cut -d "/" -f2-)"
+git -C "$ROOT_DIR" branch | grep -q "^\* $BRANCH_NAME$" \
+  || git_checkout "$BRANCH_NAME"
 
-git -C "$ROOT_DIR" checkout -q "$BRANCH_NAME" 2>/dev/null \
-  && echo "Switched to existing branch $BRANCH_NAME" \
-  || git_branch "$BRANCH_NAME"
-mkdir -p "$DEST_DIR" \
-  || exit 1
-rsync -a --delete "$SRC_DIR/" "$DEST_DIR" \
-  || exception "Unable to sync folders"
-
-[[ -z "$(git_status)" ]] \
-  && echo "No changes since last update" \
+$DRY_RUN \
   && exit
-git_commit "Copy folder $BRANCH_NAME"
-git diff --shortstat HEAD~1
+mkdir -p "$DEST_DIR" \
+  && rsync -r $VERBOSE --delete "$SRC_DIR/" "$DEST_DIR" \
+  || exit 1
+git_commit "Sync folder $BRANCH_NAME" "$VERBOSE"
